spring:
  datasource:
    url: jdbc:mysql://pb-mysql:3306/traderdb
    username: trader
    password: P@ssw0rd
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect